//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOControl.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOControl.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string AddNewModuleAdd {
            get {
                return ResourceManager.GetString("AddNewModuleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new module ähnelt.
        /// </summary>
        internal static string AddNewModuleHeader {
            get {
                return ResourceManager.GetString("AddNewModuleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string AddNewModuleSearch {
            get {
                return ResourceManager.GetString("AddNewModuleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To add a new module, either the network can be searched for DEDITEC Ethernet modules or a module can be directly added. ähnelt.
        /// </summary>
        internal static string AddNewModuleText {
            get {
                return ResourceManager.GetString("AddNewModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network scan ähnelt.
        /// </summary>
        internal static string BC_Header {
            get {
                return ResourceManager.GetString("BC_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} modules in network ähnelt.
        /// </summary>
        internal static string BC_ListViewHeader {
            get {
                return ResourceManager.GetString("BC_ListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string BC_ModuleAlreadyExist {
            get {
                return ResourceManager.GetString("BC_ModuleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        internal static string BC_Product {
            get {
                return ResourceManager.GetString("BC_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning.. ähnelt.
        /// </summary>
        internal static string BC_Scan {
            get {
                return ResourceManager.GetString("BC_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all ähnelt.
        /// </summary>
        internal static string BC_SelectAll {
            get {
                return ResourceManager.GetString("BC_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        internal static string BC_SelectNone {
            get {
                return ResourceManager.GetString("BC_SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string CFG_AddIOAlreadyExist {
            get {
                return ResourceManager.GetString("CFG_AddIOAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string CFG_AddIOHeader {
            get {
                return ResourceManager.GetString("CFG_AddIOHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new location ähnelt.
        /// </summary>
        internal static string CFG_AddNewLocationHeader {
            get {
                return ResourceManager.GetString("CFG_AddNewLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. &quot;Home&quot; ähnelt.
        /// </summary>
        internal static string CFG_AddNewLocationPlaceholder {
            get {
                return ResourceManager.GetString("CFG_AddNewLocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new location ähnelt.
        /// </summary>
        internal static string CFG_AddNewLocationText {
            get {
                return ResourceManager.GetString("CFG_AddNewLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CH{0} (name not available) ähnelt.
        /// </summary>
        internal static string CFG_ChNotAvailable {
            get {
                return ResourceManager.GetString("CFG_ChNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting entry ähnelt.
        /// </summary>
        internal static string CFG_DeleteEntryHeader {
            get {
                return ResourceManager.GetString("CFG_DeleteEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the entry &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string CFG_DeleteEntryText {
            get {
                return ResourceManager.GetString("CFG_DeleteEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit a {0} ähnelt.
        /// </summary>
        internal static string CFG_EditLocationHeader {
            get {
                return ResourceManager.GetString("CFG_EditLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a new name for {0} ähnelt.
        /// </summary>
        internal static string CFG_EditLocationText {
            get {
                return ResourceManager.GetString("CFG_EditLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die location ähnelt.
        /// </summary>
        internal static string CFG_Location {
            get {
                return ResourceManager.GetString("CFG_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an entry ähnelt.
        /// </summary>
        internal static string CFG_SelectEntry {
            get {
                return ResourceManager.GetString("CFG_SelectEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DA_InvalidValue {
            get {
                return ResourceManager.GetString("DA_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups ähnelt.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string HELP_Header {
            get {
                return ResourceManager.GetString("HELP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string HELP_HelpLocation {
            get {
                return ResourceManager.GetString("HELP_HelpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string HELP_ShowTooltip {
            get {
                return ResourceManager.GetString("HELP_ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current (0..24mA) ähnelt.
        /// </summary>
        internal static string IO_CFG_ADDA_Current {
            get {
                return ResourceManager.GetString("IO_CFG_ADDA_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voltage (±10V) ähnelt.
        /// </summary>
        internal static string IO_CFG_ADDA_Voltage {
            get {
                return ResourceManager.GetString("IO_CFG_ADDA_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string IO_CFG_Configuration {
            get {
                return ResourceManager.GetString("IO_CFG_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On/Off Switch ähnelt.
        /// </summary>
        internal static string IO_CFG_DO_OnOffSwitch {
            get {
                return ResourceManager.GetString("IO_CFG_DO_OnOffSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pushbutton ähnelt.
        /// </summary>
        internal static string IO_CFG_DO_PushButton {
            get {
                return ResourceManager.GetString("IO_CFG_DO_PushButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string IO_InvalidGroup {
            get {
                return ResourceManager.GetString("IO_InvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string IO_InvalidIOText {
            get {
                return ResourceManager.GetString("IO_InvalidIOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In-/outputs ähnelt.
        /// </summary>
        internal static string IOs {
            get {
                return ResourceManager.GetString("IOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting ähnelt.
        /// </summary>
        internal static string Main_Loading {
            get {
                return ResourceManager.GetString("Main_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analog Input ähnelt.
        /// </summary>
        internal static string Module_AI {
            get {
                return ResourceManager.GetString("Module_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analog Output ähnelt.
        /// </summary>
        internal static string Module_AO {
            get {
                return ResourceManager.GetString("Module_AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Input ähnelt.
        /// </summary>
        internal static string Module_DI {
            get {
                return ResourceManager.GetString("Module_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital Output ähnelt.
        /// </summary>
        internal static string Module_DO {
            get {
                return ResourceManager.GetString("Module_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWM Output ähnelt.
        /// </summary>
        internal static string Module_PWM {
            get {
                return ResourceManager.GetString("Module_PWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature Input ähnelt.
        /// </summary>
        internal static string Module_TEMP {
            get {
                return ResourceManager.GetString("Module_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modules ähnelt.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string MSG_Cancel {
            get {
                return ResourceManager.GetString("MSG_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string MSG_No {
            get {
                return ResourceManager.GetString("MSG_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while connecting to module {0} (IP={1}) ähnelt.
        /// </summary>
        internal static string MSG_OpenError {
            get {
                return ResourceManager.GetString("MSG_OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string MSG_PleaseWait {
            get {
                return ResourceManager.GetString("MSG_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string MSG_Yes {
            get {
                return ResourceManager.GetString("MSG_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string NAV_Appearance {
            get {
                return ResourceManager.GetString("NAV_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string NAV_Configuration {
            get {
                return ResourceManager.GetString("NAV_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string NAV_Modules {
            get {
                return ResourceManager.GetString("NAV_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string NAV_Settings {
            get {
                return ResourceManager.GetString("NAV_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new module ähnelt.
        /// </summary>
        internal static string NC_AddHeader {
            get {
                return ResourceManager.GetString("NC_AddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit modul configuration ähnelt.
        /// </summary>
        internal static string NC_EditHeader {
            get {
                return ResourceManager.GetString("NC_EditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading network configuration to the module ähnelt.
        /// </summary>
        internal static string NC_SetNewModuleConfig {
            get {
                return ResourceManager.GetString("NC_SetNewModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
